# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Hashtag.create(hashtag_name: 'サプライズ')
Hashtag.create(hashtag_name: 'デート')
Hashtag.create(hashtag_name: 'apple')
Hashtag.create(hashtag_name: 'iPhone')
Hashtag.create(hashtag_name: 'mac')
Hashtag.create(hashtag_name: 'スマホ')
Hashtag.create(hashtag_name: '周辺機器')
Hashtag.create(hashtag_name: 'イヤフォン')
Hashtag.create(hashtag_name: '便利')
Hashtag.create(hashtag_name: 'おしゃれ')
Hashtag.create(hashtag_name: 'プレゼント')
Hashtag.create(hashtag_name: 'カメラ')
Hashtag.create(hashtag_name: '日用品')
Hashtag.create(hashtag_name: '工具')
Hashtag.create(hashtag_name: '本')
Hashtag.create(hashtag_name: 'lifehack')
Hashtag.create(hashtag_name: '音楽')
Hashtag.create(hashtag_name: '文房具')
Hashtag.create(hashtag_name: '漫画')
Hashtag.create(hashtag_name: 'ビジネス')
Hashtag.create(hashtag_name: '筋トレ')
Hashtag.create(hashtag_name: 'スポーツ')
Hashtag.create(hashtag_name: '健康')
Hashtag.create(hashtag_name: 'ランニング')
Hashtag.create(hashtag_name: 'スピーカー')
Hashtag.create(hashtag_name: '美容')
Hashtag.create(hashtag_name: 'キッチン')
Hashtag.create(hashtag_name: '家具')
Hashtag.create(hashtag_name: 'キャンプ')
Hashtag.create(hashtag_name: 'アウトドア')
Hashtag.create(hashtag_name: '春')
Hashtag.create(hashtag_name: '夏')
Hashtag.create(hashtag_name: '秋')
Hashtag.create(hashtag_name: '冬')
Hashtag.create(hashtag_name: '海')
Hashtag.create(hashtag_name: '山')
Hashtag.create(hashtag_name: '旅行')
Hashtag.create(hashtag_name: 'ガジェット')
Hashtag.create(hashtag_name: '防災')
Hashtag.create(hashtag_name: '食べ物')
Hashtag.create(hashtag_name: 'ワイヤレス')
Hashtag.create(hashtag_name: 'まとめる')
Hashtag.create(hashtag_name: 'インテリア')
Hashtag.create(hashtag_name: 'サプリ')
Hashtag.create(hashtag_name: 'ウェアラブル')
Hashtag.create(hashtag_name: 'アクセサリ')
Hashtag.create(hashtag_name: '生活家電')
Hashtag.create(hashtag_name: '掃除')
Hashtag.create(hashtag_name: '収納')
Hashtag.create(hashtag_name: '雑貨')